# Generated by Django 6.0.7 on 2026-07-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='beneficiaires/')),
                ('type_aide', models.CharField(choices=[('alimentaire', 'Aide alimentaire'), ('medicale', 'Aide médicale'), ('educative', 'Aide éducative'), ('logement', 'Aide au logement'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=True)),
            ],
        ),
    ]
