# Generated by Django 6.0.7 on 2026-07-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('parametres', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
