# Generated by Django 6.0.7 on 2026-07-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='gallery/')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('statut', models.BooleanField(default=True)),
            ],
        ),
    ]
