# Generated by Django 6.0.7 on 2026-09-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='categorie',
            field=models.CharField(blank=True, default='Général', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10),
        ),
    ]
