# Generated by Django 6.0.7 on 2026-08-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False, help_text="Compte approuvé par l'administrateur. Requis pour se connecter."),
        ),
    ]
