# Generated by Django 6.0.7 on 2026-09-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_incidentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('branch', models.CharField(default='Canada', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('photo_url', models.CharField(blank=True, default='', help_text="Chemin statique ou URL d'image", max_length=500)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True, default='')),
                ('missions', models.JSONField(blank=True, default=list)),
                ('icon_type', models.CharField(blank=True, default='shield', max_length=50)),
                ('color_theme', models.CharField(blank=True, default='yellow', max_length=50)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
