# Generated by Django 6.0.7 on 2026-09-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.CharField(blank=True, default="🇹🇩 N'Djamena (Tchad)", max_length=150),
        ),
    ]
