# Generated by Django 6.0.7 on 2026-07-30 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectif', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collecte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('terminee', 'Terminée'), ('a_venir', 'À venir')], default='a_venir', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='projects.projet')),
            ],
        ),
    ]
